# Import required library

In [1]:
import pandas as pd
import numpy as np


# Import CSV file

In [2]:
df=pd.read_csv("placement.csv")

In [3]:
df.head(46)

Student_ID  CGPA   IQ  Placement
0            1   6.8  123          1
1            2   5.9  106          0
2            3   5.3  121          0
3            4   7.4  132          1
4            5   5.8  142          0
5            6   7.1   48          1
6            7   5.7  143          0
7            8   5.0   63          0
8            9   6.1  156          0
9           10   5.1   66          0
10          11   6.0   45          1
11          12   6.9  138          1
12          13   5.4  139          0
13          14   6.4  116          1
14          15   6.1  103          0
15          16   5.1  176          0
16          17   5.2  224          0
17          18   3.3  183          0
18          19   4.0  100          0
19          20   5.2  132          0
20          21   6.6  120          1
21          22   7.1  151          1
22          23   4.9  120          0
23          24   4.7   87          0
24          25   4.7  121          0
25          26   5.0   91          0
26          27   7.0  199          1
27          28   6.0  124          1
28          29   5.2   90          0
29          30   7.0  112          1
30          31   7.6  128          1
31          32   3.9  109          0
32          33   7.0  139          1
33          34   6.0  149          0
34          35   4.8  163          0
35          36   6.8   90          1
36          37   5.7  140          0
37          38   8.1  149          1
38          39   6.5  160          1
39          40   4.6  146          0
40          41   4.9  134          0
41          42   5.4  114          0
42          43   7.6   89          1
43          44   6.8  141          1
44          45   7.5   61          1
45          46   6.0   66          1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Student_ID  100 non-null    int64  
 1   CGPA        100 non-null    float64
 2   IQ          100 non-null    int64  
 3   Placement   100 non-null    int64  
dtypes: float64(1), int64(3)
memory usage: 3.2 KB


In [5]:
df.isnull().sum()

Student_ID    0
CGPA          0
IQ            0
Placement     0
dtype: int64

# Getting the Statistics Summmary

In [6]:
df.describe()

Student_ID        CGPA          IQ   Placement
count  100.000000  100.000000  100.000000  100.000000
mean    50.500000    5.991000  123.580000    0.500000
std     29.011492    1.143634   39.944198    0.502519
min      1.000000    3.300000   37.000000    0.000000
25%     25.750000    5.075000  101.500000    0.000000
50%     50.500000    6.000000  127.500000    0.500000
75%     75.250000    6.900000  149.000000    1.000000
max    100.000000    8.500000  233.000000    1.000000

In [7]:
df.columns

Index(['Student_ID', 'CGPA', 'IQ', 'Placement'], dtype='object')

In [8]:
df.shape

(100, 4)

In [9]:
df["Placement"].value_counts()

1    50
0    50
Name: Placement, dtype: int64

In [10]:
df.groupby("Placement").mean()

Student_ID   CGPA      IQ
Placement                           
0               46.32  5.056  126.88
1               54.68  6.926  120.28

# finding Dependent and Independent Variables

In [11]:
y=df["Placement"]

In [12]:
y.shape

(100,)

In [13]:
y

0     1
1     0
2     0
3     1
4     0
     ..
95    0
96    0
97    1
98    1
99    1
Name: Placement, Length: 100, dtype: int64

In [14]:
X=df[["CGPA","IQ"]]

In [15]:
X.shape

(100, 2)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
ss=StandardScaler()

In [18]:
X=ss.fit_transform(X)

In [19]:
X

array([[ 0.71095807, -0.01459341],
       [-0.0799718 , -0.44233119],
       [-0.60725838, -0.0649155 ],
       [ 1.23824465,  0.21185601],
       [-0.16785289,  0.46346647],
       [ 0.97460136, -1.90167186],
       [-0.25573399,  0.48862751],
       [-0.87090167, -1.52425617],
       [ 0.0957904 ,  0.81572111],
       [-0.78302057, -1.44877303],
       [ 0.0079093 , -1.977155  ],
       [ 0.79883917,  0.36282228],
       [-0.51937728,  0.38798333],
       [ 0.35943369, -0.19072073],
       [ 0.0957904 , -0.51781433],
       [-0.78302057,  1.31894203],
       [-0.69513948,  2.52667224],
       [-2.36488031,  1.49506935],
       [-1.74971264, -0.59329747],
       [-0.69513948,  0.21185601],
       [ 0.53519588, -0.09007654],
       [ 0.97460136,  0.68991588],
       [-0.95878277, -0.09007654],
       [-1.13454496, -0.92039106],
       [-1.13454496, -0.0649155 ],
       [-0.87090167, -0.81974688],
       [ 0.88672027,  1.89764609],
       [ 0.0079093 ,  0.01056764],
       [-0.69513948,

# Getting Train and Test Set

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,random_state=2529)

In [22]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((70, 2), (30, 2), (70,), (30,))

# Model Training

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
lr=LogisticRegression()

In [25]:
lr.fit(X_train,y_train)

LogisticRegression()

# Model Prediction

In [26]:
y_pred=lr.predict(X_test)

In [27]:
y_pred

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1], dtype=int64)

In [28]:
lr.predict_proba(X_test)

array([[0.14625283, 0.85374717],
       [0.93627665, 0.06372335],
       [0.31225355, 0.68774645],
       [0.85921675, 0.14078325],
       [0.55859556, 0.44140444],
       [0.59855708, 0.40144292],
       [0.03230864, 0.96769136],
       [0.36854121, 0.63145879],
       [0.00221892, 0.99778108],
       [0.94998577, 0.05001423],
       [0.71998293, 0.28001707],
       [0.06678211, 0.93321789],
       [0.24280142, 0.75719858],
       [0.9766201 , 0.0233799 ],
       [0.38513856, 0.61486144],
       [0.28100947, 0.71899053],
       [0.36919946, 0.63080054],
       [0.9505204 , 0.0494796 ],
       [0.66663238, 0.33336762],
       [0.84791247, 0.15208753],
       [0.88526065, 0.11473935],
       [0.00321788, 0.99678212],
       [0.03402257, 0.96597743],
       [0.12203804, 0.87796196],
       [0.07455692, 0.92544308],
       [0.96120589, 0.03879411],
       [0.95991072, 0.04008928],
       [0.43982882, 0.56017118],
       [0.91414187, 0.08585813],
       [0.21780653, 0.78219347]])

# Model Evaluation

In [29]:
from sklearn.metrics import classification_report,confusion_matrix

In [30]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 2 16]]


In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      1.00      0.92        12
           1       1.00      0.89      0.94        18

    accuracy                           0.93        30
   macro avg       0.93      0.94      0.93        30
weighted avg       0.94      0.93      0.93        30



In [32]:
#Checking Accuracy of our model(1st Prediction)

In [33]:
X_new=df.iloc[20:21,1:3]

In [34]:
X_new

CGPA   IQ
20   6.6  120

In [35]:
X_new.shape

(1, 2)

In [36]:
lr.predict(X_new)

C:\Users\nainc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:413: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


array([1], dtype=int64)

In [37]:
#Checking Accuracy of our model(2nd Prediction)

In [38]:
X_new=df.iloc[15:21,1:3]

In [39]:
X_new

CGPA   IQ
15   5.1  176
16   5.2  224
17   3.3  183
18   4.0  100
19   5.2  132
20   6.6  120

In [40]:
X_new=ss.fit_transform(X_new)

In [41]:
X_new

array([[ 0.19245009,  0.47619715],
       [ 0.28867513,  1.60962508],
       [-1.53960072,  0.64148872],
       [-0.8660254 , -1.31839707],
       [ 0.28867513, -0.56277845],
       [ 1.63582576, -0.84613543]])

In [42]:
lr.predict(X_new)

array([1, 1, 0, 0, 1, 1], dtype=int64)

In [43]:
lr.predict_proba(X_new)

array([[0.4132182 , 0.5867818 ],
       [0.31942985, 0.68057015],
       [0.99044423, 0.00955577],
       [0.9484763 , 0.0515237 ],
       [0.37466132, 0.62533868],
       [0.01240347, 0.98759653]])